micronaut:
  server:
    port: -1
  http:
    services:
      mauro:
        url: 'http://localhost:2345'
#       apikey: 1234
    client:
      read-timeout: 10m      # Read timeout
      connect-timeout: 100s
  security:
    enabled: false