micronaut:
  application:
    name: sandbox
  http:
    client:
      read-timeout: 30m
      connect-timeout: 30m
  server:
    port: 8088
    max-request-size: 100mb
    multipart:
      max-file-size: 100mb
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: false
    authentication: session
    redirect:
      enabled: false
    endpoints:
      login:
        enabled: true
        path: '/authentication/login'
      logout:
        enabled: true
        path: '/authentication/logout'
        get-allowed: true
      oauth:
        enabled: false
    reject-not-found: false
    authentication-provider-strategy: any
#    Populate to enable OAuth2; see also mauro.oauth properties
#    oauth2:
#      clients:
#        keycloak:
#          client-id:
#          client-secret:
#          openid:
#            issuer:


  caches:
    items-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    security-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    api-property-cache:
      initial-capacity: 1000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true

endpoints:
  routes:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  flyway:
    enabled: true
    sensitive: true
  caches:
    enabled: true
    sensitive: true

jackson:
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: sandbox
    password: sandbox
    dialect: POSTGRES
    db-type: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
      baselineOnMigrate: true
      fail-on-missing-locations: true
      clean-schema: false
      schemas:
        - core
        - terminology
        - datamodel
        - security
        - dataflow

javamail:
  authentication:
    username: $$username$$ # Replace me!
    password: $$password$$ # Replace me!
  properties:
    mail:
      smtp:
        port: 587 # Replace me!
        auth: true
        starttls:
          enable: true
        host: $$host$$ # Replace me!

# Populate to enable OAuth2; see also micronaut.security properties
#mauro:
#  oauth:
#    id:
#    label: Keycloak
#    standard-provider: true
#    authorization-endpoint:
#    image-url:
#    login-success:

#    create-user:
