micronaut:
  application:
    name: sandbox
  http:
    client:
      read-timeout: 30m
      connect-timeout: 30m
  server:
    port: 8088
    max-request-size: 100mb
    multipart:
      max-file-size: 100mb
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: session
    redirect:
      enabled: false
    endpoints:
      login:
        enabled: true
        path: '/authentication/login'
      logout:
        enabled: true
        path: '/authentication/logout'
        get-allowed: true
      oauth:
        enabled: true
    reject-not-found: false
    authentication-provider-strategy: any
    create-user: true

    openid-provider:
      id: b2092268-3014-4c24-a9cc-0913b2c63cfb
      label: Keycloak
      standardProvider: true,
      authorizationEndpoint: http://tvssnsdedm001.oxnet.nhs.uk:8095/realms/test/protocol/openid-connect/auth?scope=openid+email+profile&response_type=code&client_id=mdm&state=3b2e1535-5cae-49f7-83c3-0032aa7539c9&nonce=6ea24466-f8f4-3089-8881-e6b76eb70d5a
      imageUrl: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png?20200311211229
    oauth2:
      clients:
        keycloak:
          client-id: mauro
          client-secret: 27wjHeD3szihjHolwgJ6QZPF7i9ZSuga
          openid:
            issuer: http://localhost:9009/realms/master
  caches:
    items-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    security-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    api-property-cache:
      initial-capacity: 1000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true

endpoints:
  routes:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  flyway:
    enabled: true
    sensitive: true
  caches:
    enabled: true
    sensitive: true

jackson:
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: sandbox
    password: sandbox
    dialect: POSTGRES
    db-type: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
      baselineOnMigrate: true
      fail-on-missing-locations: true
      clean-schema: false
      schemas:
        - core
        - terminology
        - datamodel
        - security
        - dataflow
javamail:
  authentication:
    username: $$username$$ # Replace me!
    password: $$password$$ # Replace me!
  properties:
    mail:
      smtp:
        port: 587 # Replace me!
        auth: true
        starttls:
          enable: true
        host: $$host$$ # Replace me!
