micronaut:
  application:
    name: sandbox
  server:
    port: 8088
    max-request-size: 100mb
    multipart:
      max-file-size: 100mb
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: false # TODO: enable security
    authentication: session
    redirect:
      enabled: false
    endpoints:
      login:
        enabled: true
        path: '/authentication/login'
    reject-not-found: false

#  caches:
#    items-cache:
#      maximum-size: 100
ehcache:
  caches:
    items-cache:
      enabled: true
      heap:
        max-items: 10000
        size-of-max-object-size: 1000000
#netty:
#  default:
#    allocator:
#      max-order: 3
endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  flyway:
    enabled: true
    sensitive: false
  caches:
    enabled: true
    sensitive: false

jackson:
  serialization:
    writeDatesAsTimestamps: false
# JDBC configuration needed for Flyway
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: sandbox
    password: sandbox
    dialect: POSTGRES
    db-type: postgres
    driver-class-name: org.postgresql.Driver
r2dbc:
  datasources:
    default:
      url: r2dbc:pool://localhost:5432/sandbox
      username: sandbox
      password: sandbox
      schema-generate: none
      dialect: POSTGRES
      db-type: postgres
      options:
        driver: pool
        protocol: postgres
flyway:
  datasources:
    default:
      enabled: true
      baselineOnMigrate: true
      fail-on-missing-locations: true
      clean-schema: false
      schemas:
        - core
        - terminology
        - datamodel
        - security
javamail:
  smtp:
    host: smtp.gmail.com
    port: 587
    transportstrategy: SMTP_TLS
  authentication:
    username: 'user@gmail.com'
    password: 'password'
  properties:
    mail:
      smtp:
        port: 587
        auth: true
        starttls:
          enable: true
        host: smtp.gmail.com