micronaut:
  application:
    name: sandbox
    client:
      connect-timeout: 11s

  server:
    port: 8088
    max-request-size: 1gb
    multipart:
      max-file-size: 1gb
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: session
    redirect:
      enabled: false
    endpoints:
      login:
        enabled: true
        path: '/authentication/login'
      logout:
        enabled: true
        path: '/authentication/logout'
        get-allowed: true
      oauth:
        enabled: true
    reject-not-found: false
    authentication-provider-strategy: any
#    Populate to enable OAuth2; see also mauro.oauth properties
    oauth2:
      clients:
        keycloak:
          client-id: mdm
          client-secret: 4b3b7290-7629-4b88-b310-df256adc8fed
          openid:
            issuer: http://localhost:8095/realms/test

  caches:
    items-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    security-cache:
      initial-capacity: 10000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true
    api-property-cache:
      initial-capacity: 1000
      maximum-weight: 1_000_000_000
      expire-after-write: 1h
      record-stats: true

endpoints:
  routes:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  flyway:
    enabled: true
    sensitive: true
  caches:
    enabled: true
    sensitive: true

jackson:
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: sandbox
    password: sandbox
    dialect: POSTGRES
    db-type: postgres
    driver-class-name: org.postgresql.Driver


javamail:
  authentication:
    username: $$username$$ # Replace me!
    password: $$password$$ # Replace me!
  properties:
    mail:
      smtp:
        port: 587 # Replace me!
        auth: true
        starttls:
          enable: true
        host: $$host$$ # Replace me!

mauro:
  federation:
    subscribed-catalogues.max: 50
  audit:
    scope: ALL

# Populate to enable OAuth2; see also micronaut.security properties
#  oauth:
#    id:
#    label: Keycloak
#    standard-provider: true
#    authorization-endpoint:
#    image-url:
#    login-success:
#    create-user:
mauro:
  oauth:
    id: 00000000-0000-0000-0000-000000000000
    label: Keycloak
    standard-provider: true
    authorization-endpoint: http://localhost:8088/oauth/login/keycloak
    image-url: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png?20200311211229
    create-user: true
    login-success: http://localhost:4201/redirects/open-id-connect-redirect.html
