micronaut:
  application:
    name: sandbox
  server:
    port: 8088
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  routes:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
jackson:
  serialization:
    writeDatesAsTimestamps: false
r2dbc:
  datasources:
    default:
      url: r2dbc:pool://localhost:5432/sandbox
      username: sandbox
      password: sandbox
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
      options:
        driver: pool
        protocol: postgres