micronaut:
  server:
    port: 8088
  security:
    enabled: true
    redirect:
      enabled: true
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: ${OAUTH_CLIENT_ID:sandbox}
          client-secret: ${OAUTH_CLIENT_SECRET:FR5Xz0TaymuAyPxGIqFRhf8HpBtwyOVi}
          openid:
            issuer: ${OIDC_ISSUER_DOMAIN:`http://localhost:9009`}/realms/${KEYCLOAK_REALM:master}
    endpoints:
      logout:
        path:
          /logout
        get-allowed: true